2023-12-12 22:17:53,170 WARNING discord.client PyNaCl is not installed, voice will NOT be supported
2023-12-12 22:17:53,173 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): pypi.org:443
2023-12-12 22:17:53,233 DEBUG urllib3.connectionpool https://pypi.org:443 "GET /pypi/praw/json HTTP/1.1" 200 35659
2023-12-12 22:17:53,325 DEBUG discord.client on_ready has successfully been registered as an event
2023-12-12 22:17:53,325 DEBUG discord.client on_member_join has successfully been registered as an event
2023-12-12 22:17:53,325 DEBUG discord.client on_message has successfully been registered as an event
2023-12-12 22:17:53,326 DEBUG asyncio Using proactor: IocpProactor
2023-12-12 22:17:53,328 INFO discord.client logging in using static token
2023-12-12 22:17:53,506 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.239:8080
2023-12-12 22:17:53,506 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-12-12 22:17:55,295 INFO discord.gateway Shard ID None has connected to Gateway (Session ID: 3b1c04fa1417742e09ea3c24932eb392).
2023-12-12 22:18:18,504 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:18:18,504 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/197/hot at 1702419498.5045137
2023-12-12 22:18:18,504 DEBUG prawcore Data: None
2023-12-12 22:18:18,505 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:18:18,506 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): www.reddit.com:443
2023-12-12 22:18:18,672 DEBUG urllib3.connectionpool https://www.reddit.com:443 "POST /api/v1/access_token HTTP/1.1" 200 651
2023-12-12 22:18:18,674 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): oauth.reddit.com:443
2023-12-12 22:18:19,900 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/197/hot?limit=200&raw_json=1 HTTP/1.1" 200 60600
2023-12-12 22:18:20,055 DEBUG prawcore Response: 200 (60600 bytes) (rst-98:rem-599.0:used-1 ratelimit) at 1702419500.0555031
2023-12-12 22:18:20,067 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:18:20,067 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/197/hot at 1702419500.0675044
2023-12-12 22:18:20,067 DEBUG prawcore Data: None
2023-12-12 22:18:20,068 DEBUG prawcore Params: {'after': 't3_18eutzk', 'limit': 200, 'raw_json': 1}
2023-12-12 22:18:21,401 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/197/hot?limit=200&after=t3_18eutzk&raw_json=1 HTTP/1.1" 200 60152
2023-12-12 22:18:21,483 DEBUG prawcore Response: 200 (60152 bytes) (rst-97:rem-598.0:used-2 ratelimit) at 1702419501.4835598
2023-12-12 22:18:22,984 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:18:22,984 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/newyorknine/hot at 1702419502.984501
2023-12-12 22:18:22,984 DEBUG prawcore Data: None
2023-12-12 22:18:22,984 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:18:24,449 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/newyorknine/hot?limit=200&raw_json=1 HTTP/1.1" 200 94991
2023-12-12 22:18:24,540 DEBUG prawcore Response: 200 (94991 bytes) (rst-94:rem-597.0:used-3 ratelimit) at 1702419504.5400686
2023-12-12 22:18:24,553 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:18:24,553 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/newyorknine/hot at 1702419504.5535712
2023-12-12 22:18:24,554 DEBUG prawcore Data: None
2023-12-12 22:18:24,554 DEBUG prawcore Params: {'after': 't3_18esdpe', 'limit': 200, 'raw_json': 1}
2023-12-12 22:18:26,047 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/newyorknine/hot?limit=200&after=t3_18esdpe&raw_json=1 HTTP/1.1" 200 88694
2023-12-12 22:18:26,138 DEBUG prawcore Response: 200 (88694 bytes) (rst-93:rem-596.0:used-4 ratelimit) at 1702419506.1380124
2023-12-12 22:22:51,886 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:22:51,886 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419771.8865082
2023-12-12 22:22:51,886 DEBUG prawcore Data: None
2023-12-12 22:22:51,887 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:22:53,519 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&raw_json=1 HTTP/1.1" 200 71074
2023-12-12 22:22:53,612 DEBUG prawcore Response: 200 (71074 bytes) (rst-425:rem-599.0:used-1 ratelimit) at 1702419773.6125083
2023-12-12 22:22:53,625 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:22:53,625 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419773.6250107
2023-12-12 22:22:53,625 DEBUG prawcore Data: None
2023-12-12 22:22:53,625 DEBUG prawcore Params: {'after': 't3_18fhlio', 'limit': 200, 'raw_json': 1}
2023-12-12 22:22:55,060 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&after=t3_18fhlio&raw_json=1 HTTP/1.1" 200 74288
2023-12-12 22:22:55,196 DEBUG prawcore Response: 200 (74288 bytes) (rst-423:rem-598.0:used-2 ratelimit) at 1702419775.1960018
2023-12-12 22:22:55,208 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:22:55,208 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419775.208504
2023-12-12 22:22:55,209 DEBUG prawcore Data: None
2023-12-12 22:22:55,209 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:22:56,639 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&raw_json=1 HTTP/1.1" 200 71030
2023-12-12 22:22:56,723 DEBUG prawcore Response: 200 (71030 bytes) (rst-422:rem-597.0:used-3 ratelimit) at 1702419776.7230022
2023-12-12 22:22:56,734 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:22:56,734 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419776.7345042
2023-12-12 22:22:56,734 DEBUG prawcore Data: None
2023-12-12 22:22:56,734 DEBUG prawcore Params: {'after': 't3_18fhlio', 'limit': 200, 'raw_json': 1}
2023-12-12 22:22:58,251 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&after=t3_18fhlio&raw_json=1 HTTP/1.1" 200 74319
2023-12-12 22:22:58,338 DEBUG prawcore Response: 200 (74319 bytes) (rst-420:rem-596.0:used-4 ratelimit) at 1702419778.3380024
2023-12-12 22:22:58,350 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:22:58,350 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419778.3505044
2023-12-12 22:22:58,350 DEBUG prawcore Data: None
2023-12-12 22:22:58,350 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:22:59,687 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&raw_json=1 HTTP/1.1" 200 70993
2023-12-12 22:22:59,768 DEBUG prawcore Response: 200 (70993 bytes) (rst-419:rem-595.0:used-5 ratelimit) at 1702419779.7680018
2023-12-12 22:22:59,780 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:22:59,781 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419779.7810037
2023-12-12 22:22:59,781 DEBUG prawcore Data: None
2023-12-12 22:22:59,781 DEBUG prawcore Params: {'after': 't3_18fhlio', 'limit': 200, 'raw_json': 1}
2023-12-12 22:23:00,990 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&after=t3_18fhlio&raw_json=1 HTTP/1.1" 200 74263
2023-12-12 22:23:01,076 DEBUG prawcore Response: 200 (74263 bytes) (rst-417:rem-594.0:used-6 ratelimit) at 1702419781.07649
2023-12-12 22:23:01,088 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:23:01,088 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419781.0889926
2023-12-12 22:23:01,088 DEBUG prawcore Data: None
2023-12-12 22:23:01,088 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:23:02,539 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&raw_json=1 HTTP/1.1" 200 70999
2023-12-12 22:23:02,632 DEBUG prawcore Response: 200 (70999 bytes) (rst-416:rem-593.0:used-7 ratelimit) at 1702419782.6329715
2023-12-12 22:23:02,643 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:23:02,643 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419782.643974
2023-12-12 22:23:02,643 DEBUG prawcore Data: None
2023-12-12 22:23:02,643 DEBUG prawcore Params: {'after': 't3_18fhlio', 'limit': 200, 'raw_json': 1}
2023-12-12 22:23:04,373 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&after=t3_18fhlio&raw_json=1 HTTP/1.1" 200 74232
2023-12-12 22:23:04,456 DEBUG prawcore Response: 200 (74232 bytes) (rst-414:rem-592.0:used-8 ratelimit) at 1702419784.4569995
2023-12-12 22:23:04,469 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:23:04,469 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419784.4690027
2023-12-12 22:23:04,469 DEBUG prawcore Data: None
2023-12-12 22:23:04,469 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:23:06,341 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&raw_json=1 HTTP/1.1" 200 73589
2023-12-12 22:23:06,423 DEBUG prawcore Response: 200 (73589 bytes) (rst-412:rem-591.0:used-9 ratelimit) at 1702419786.4234807
2023-12-12 22:23:06,435 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:23:06,435 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419786.435483
2023-12-12 22:23:06,435 DEBUG prawcore Data: None
2023-12-12 22:23:06,435 DEBUG prawcore Params: {'after': 't3_18fc6wy', 'limit': 200, 'raw_json': 1}
2023-12-12 22:23:07,687 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&after=t3_18fc6wy&raw_json=1 HTTP/1.1" 200 71773
2023-12-12 22:23:07,772 DEBUG prawcore Response: 200 (71773 bytes) (rst-411:rem-590.0:used-10 ratelimit) at 1702419787.7720068
2023-12-12 22:23:07,784 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:23:07,785 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419787.785009
2023-12-12 22:23:07,785 DEBUG prawcore Data: None
2023-12-12 22:23:07,785 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:23:09,064 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&raw_json=1 HTTP/1.1" 200 73552
2023-12-12 22:23:09,161 DEBUG prawcore Response: 200 (73552 bytes) (rst-409:rem-589.0:used-11 ratelimit) at 1702419789.1610024
2023-12-12 22:23:09,173 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:23:09,173 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419789.1730046
2023-12-12 22:23:09,173 DEBUG prawcore Data: None
2023-12-12 22:23:09,173 DEBUG prawcore Params: {'after': 't3_18fc6wy', 'limit': 200, 'raw_json': 1}
2023-12-12 22:23:10,609 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&after=t3_18fc6wy&raw_json=1 HTTP/1.1" 200 71716
2023-12-12 22:23:10,698 DEBUG prawcore Response: 200 (71716 bytes) (rst-408:rem-588.0:used-12 ratelimit) at 1702419790.6989744
2023-12-12 22:23:10,710 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:23:10,710 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419790.7109768
2023-12-12 22:23:10,710 DEBUG prawcore Data: None
2023-12-12 22:23:10,710 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:23:12,131 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&raw_json=1 HTTP/1.1" 200 73457
2023-12-12 22:23:12,214 DEBUG prawcore Response: 200 (73457 bytes) (rst-406:rem-587.0:used-13 ratelimit) at 1702419792.214251
2023-12-12 22:23:12,225 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:23:12,226 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419792.226254
2023-12-12 22:23:12,226 DEBUG prawcore Data: None
2023-12-12 22:23:12,226 DEBUG prawcore Params: {'after': 't3_18fc6wy', 'limit': 200, 'raw_json': 1}
2023-12-12 22:23:13,663 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&after=t3_18fc6wy&raw_json=1 HTTP/1.1" 200 71694
2023-12-12 22:23:13,750 DEBUG prawcore Response: 200 (71694 bytes) (rst-405:rem-586.0:used-14 ratelimit) at 1702419793.7500122
2023-12-12 22:23:13,762 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:23:13,762 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419793.7625134
2023-12-12 22:23:13,762 DEBUG prawcore Data: None
2023-12-12 22:23:13,762 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:23:15,086 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&raw_json=1 HTTP/1.1" 200 73514
2023-12-12 22:23:15,243 DEBUG prawcore Response: 200 (73514 bytes) (rst-403:rem-585.0:used-15 ratelimit) at 1702419795.2430046
2023-12-12 22:23:15,254 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:23:15,255 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419795.2550073
2023-12-12 22:23:15,255 DEBUG prawcore Data: None
2023-12-12 22:23:15,255 DEBUG prawcore Params: {'after': 't3_18fc6wy', 'limit': 200, 'raw_json': 1}
2023-12-12 22:23:16,535 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&after=t3_18fc6wy&raw_json=1 HTTP/1.1" 200 71734
2023-12-12 22:23:16,618 DEBUG prawcore Response: 200 (71734 bytes) (rst-402:rem-584.0:used-16 ratelimit) at 1702419796.6189928
2023-12-12 22:23:16,631 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:23:16,631 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419796.631495
2023-12-12 22:23:16,631 DEBUG prawcore Data: None
2023-12-12 22:23:16,631 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:23:18,361 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&raw_json=1 HTTP/1.1" 200 73648
2023-12-12 22:23:18,446 DEBUG prawcore Response: 200 (73648 bytes) (rst-400:rem-583.0:used-17 ratelimit) at 1702419798.4465005
2023-12-12 22:23:18,479 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:23:18,479 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419798.4790068
2023-12-12 22:23:18,479 DEBUG prawcore Data: None
2023-12-12 22:23:18,479 DEBUG prawcore Params: {'after': 't3_18fc6wy', 'limit': 200, 'raw_json': 1}
2023-12-12 22:23:19,751 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&after=t3_18fc6wy&raw_json=1 HTTP/1.1" 200 71669
2023-12-12 22:23:19,834 DEBUG prawcore Response: 200 (71669 bytes) (rst-399:rem-582.0:used-18 ratelimit) at 1702419799.8345175
2023-12-12 22:23:19,847 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:23:19,847 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419799.8470204
2023-12-12 22:23:19,847 DEBUG prawcore Data: None
2023-12-12 22:23:19,847 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:23:21,097 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&raw_json=1 HTTP/1.1" 200 73442
2023-12-12 22:23:21,183 DEBUG prawcore Response: 200 (73442 bytes) (rst-397:rem-581.0:used-19 ratelimit) at 1702419801.18344
2023-12-12 22:23:21,194 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:23:21,194 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702419801.194942
2023-12-12 22:23:21,194 DEBUG prawcore Data: None
2023-12-12 22:23:21,194 DEBUG prawcore Params: {'after': 't3_18fc6wy', 'limit': 200, 'raw_json': 1}
2023-12-12 22:23:22,406 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&after=t3_18fc6wy&raw_json=1 HTTP/1.1" 200 71747
2023-12-12 22:23:22,489 DEBUG prawcore Response: 200 (71747 bytes) (rst-396:rem-580.0:used-20 ratelimit) at 1702419802.4899888
2023-12-12 22:23:22,502 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:23:22,502 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/newyorknine/hot at 1702419802.5029912
2023-12-12 22:23:22,503 DEBUG prawcore Data: None
2023-12-12 22:23:22,503 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:23:24,023 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/newyorknine/hot?limit=200&raw_json=1 HTTP/1.1" 200 94958
2023-12-12 22:23:24,118 DEBUG prawcore Response: 200 (94958 bytes) (rst-395:rem-579.0:used-21 ratelimit) at 1702419804.1185412
2023-12-12 22:23:24,133 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:23:24,133 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/newyorknine/hot at 1702419804.1335437
2023-12-12 22:23:24,133 DEBUG prawcore Data: None
2023-12-12 22:23:24,134 DEBUG prawcore Params: {'after': 't3_18esdpe', 'limit': 200, 'raw_json': 1}
2023-12-12 22:23:25,476 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/newyorknine/hot?limit=200&after=t3_18esdpe&raw_json=1 HTTP/1.1" 200 88687
2023-12-12 22:23:25,562 DEBUG prawcore Response: 200 (88687 bytes) (rst-393:rem-578.0:used-22 ratelimit) at 1702419805.562994
2023-12-12 22:27:21,870 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:27:21,871 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702420041.8715005
2023-12-12 22:27:21,871 DEBUG prawcore Data: None
2023-12-12 22:27:21,871 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:27:24,471 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&raw_json=1 HTTP/1.1" 200 73573
2023-12-12 22:27:24,567 DEBUG prawcore Response: 200 (73573 bytes) (rst-155:rem-577.0:used-23 ratelimit) at 1702420044.5675864
2023-12-12 22:27:24,579 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:27:24,580 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702420044.5800884
2023-12-12 22:27:24,580 DEBUG prawcore Data: None
2023-12-12 22:27:24,580 DEBUG prawcore Params: {'after': 't3_18fc6wy', 'limit': 200, 'raw_json': 1}
2023-12-12 22:27:26,205 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&after=t3_18fc6wy&raw_json=1 HTTP/1.1" 200 71613
2023-12-12 22:27:26,365 DEBUG prawcore Response: 200 (71613 bytes) (rst-152:rem-576.0:used-24 ratelimit) at 1702420046.3653772
2023-12-12 22:27:26,378 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:27:26,378 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702420046.378881
2023-12-12 22:27:26,378 DEBUG prawcore Data: None
2023-12-12 22:27:26,378 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:27:27,679 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&raw_json=1 HTTP/1.1" 200 73529
2023-12-12 22:27:27,849 DEBUG prawcore Response: 200 (73529 bytes) (rst-151:rem-575.0:used-25 ratelimit) at 1702420047.849487
2023-12-12 22:27:27,861 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:27:27,861 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702420047.8619893
2023-12-12 22:27:27,861 DEBUG prawcore Data: None
2023-12-12 22:27:27,861 DEBUG prawcore Params: {'after': 't3_18fc6wy', 'limit': 200, 'raw_json': 1}
2023-12-12 22:27:29,151 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&after=t3_18fc6wy&raw_json=1 HTTP/1.1" 200 71658
2023-12-12 22:27:29,238 DEBUG prawcore Response: 200 (71658 bytes) (rst-149:rem-574.0:used-26 ratelimit) at 1702420049.2389948
2023-12-12 22:27:32,976 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:27:32,976 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702420052.976503
2023-12-12 22:27:32,976 DEBUG prawcore Data: None
2023-12-12 22:27:32,976 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:27:34,862 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&raw_json=1 HTTP/1.1" 200 73492
2023-12-12 22:27:34,953 DEBUG prawcore Response: 200 (73492 bytes) (rst-144:rem-573.0:used-27 ratelimit) at 1702420054.953595
2023-12-12 22:27:34,965 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:27:34,965 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702420054.965597
2023-12-12 22:27:34,965 DEBUG prawcore Data: None
2023-12-12 22:27:34,966 DEBUG prawcore Params: {'after': 't3_18fc6wy', 'limit': 200, 'raw_json': 1}
2023-12-12 22:27:36,319 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&after=t3_18fc6wy&raw_json=1 HTTP/1.1" 200 71692
2023-12-12 22:27:36,409 DEBUG prawcore Response: 200 (71692 bytes) (rst-142:rem-572.0:used-28 ratelimit) at 1702420056.4095025
2023-12-12 22:27:36,422 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:27:36,422 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702420056.422005
2023-12-12 22:27:36,422 DEBUG prawcore Data: None
2023-12-12 22:27:36,422 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:27:37,611 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&raw_json=1 HTTP/1.1" 200 73511
2023-12-12 22:27:37,697 DEBUG prawcore Response: 200 (73511 bytes) (rst-141:rem-571.0:used-29 ratelimit) at 1702420057.6975026
2023-12-12 22:27:37,709 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:27:37,709 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702420057.709505
2023-12-12 22:27:37,709 DEBUG prawcore Data: None
2023-12-12 22:27:37,709 DEBUG prawcore Params: {'after': 't3_18fc6wy', 'limit': 200, 'raw_json': 1}
2023-12-12 22:27:39,037 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&after=t3_18fc6wy&raw_json=1 HTTP/1.1" 200 71711
2023-12-12 22:27:39,123 DEBUG prawcore Response: 200 (71711 bytes) (rst-139:rem-570.0:used-30 ratelimit) at 1702420059.1230023
2023-12-12 22:27:39,135 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:27:39,135 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702420059.1355045
2023-12-12 22:27:39,136 DEBUG prawcore Data: None
2023-12-12 22:27:39,136 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-12 22:27:40,356 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&raw_json=1 HTTP/1.1" 200 73601
2023-12-12 22:27:40,446 DEBUG prawcore Response: 200 (73601 bytes) (rst-138:rem-569.0:used-31 ratelimit) at 1702420060.4460022
2023-12-12 22:27:40,458 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-12 22:27:40,458 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/awww/hot at 1702420060.4580045
2023-12-12 22:27:40,458 DEBUG prawcore Data: None
2023-12-12 22:27:40,458 DEBUG prawcore Params: {'after': 't3_18fc6wy', 'limit': 200, 'raw_json': 1}
2023-12-12 22:27:41,819 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/awww/hot?limit=200&after=t3_18fc6wy&raw_json=1 HTTP/1.1" 200 71717
2023-12-12 22:27:41,908 DEBUG prawcore Response: 200 (71717 bytes) (rst-137:rem-568.0:used-32 ratelimit) at 1702420061.9080026
2023-12-12 22:31:18,251 WARNING discord.gateway Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:31:28,258 WARNING discord.gateway Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:31:38,263 WARNING discord.gateway Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:31:48,272 WARNING discord.gateway Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:31:58,276 WARNING discord.gateway Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:32:08,288 WARNING discord.gateway Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:32:18,303 WARNING discord.gateway Shard ID None heartbeat blocked for more than 70 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:32:28,313 WARNING discord.gateway Shard ID None heartbeat blocked for more than 80 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:32:38,328 WARNING discord.gateway Shard ID None heartbeat blocked for more than 90 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:32:48,337 WARNING discord.gateway Shard ID None heartbeat blocked for more than 100 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:32:58,342 WARNING discord.gateway Shard ID None heartbeat blocked for more than 110 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:33:08,355 WARNING discord.gateway Shard ID None heartbeat blocked for more than 120 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:33:18,359 WARNING discord.gateway Shard ID None heartbeat blocked for more than 130 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:33:28,371 WARNING discord.gateway Shard ID None heartbeat blocked for more than 140 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:33:38,382 WARNING discord.gateway Shard ID None heartbeat blocked for more than 150 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:33:48,386 WARNING discord.gateway Shard ID None heartbeat blocked for more than 160 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:33:58,397 WARNING discord.gateway Shard ID None heartbeat blocked for more than 170 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:34:08,407 WARNING discord.gateway Shard ID None heartbeat blocked for more than 180 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:34:18,413 WARNING discord.gateway Shard ID None heartbeat blocked for more than 190 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:34:28,421 WARNING discord.gateway Shard ID None heartbeat blocked for more than 200 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:34:38,437 WARNING discord.gateway Shard ID None heartbeat blocked for more than 210 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:34:48,445 WARNING discord.gateway Shard ID None heartbeat blocked for more than 220 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:34:58,453 WARNING discord.gateway Shard ID None heartbeat blocked for more than 230 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:35:08,463 WARNING discord.gateway Shard ID None heartbeat blocked for more than 240 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:35:18,469 WARNING discord.gateway Shard ID None heartbeat blocked for more than 250 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:35:28,475 WARNING discord.gateway Shard ID None heartbeat blocked for more than 260 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:35:38,485 WARNING discord.gateway Shard ID None heartbeat blocked for more than 270 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:35:48,496 WARNING discord.gateway Shard ID None heartbeat blocked for more than 280 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:35:58,499 WARNING discord.gateway Shard ID None heartbeat blocked for more than 290 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:36:08,506 WARNING discord.gateway Shard ID None heartbeat blocked for more than 300 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:36:18,521 WARNING discord.gateway Shard ID None heartbeat blocked for more than 310 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:36:28,525 WARNING discord.gateway Shard ID None heartbeat blocked for more than 320 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:36:38,541 WARNING discord.gateway Shard ID None heartbeat blocked for more than 330 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:36:48,552 WARNING discord.gateway Shard ID None heartbeat blocked for more than 340 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:36:58,555 WARNING discord.gateway Shard ID None heartbeat blocked for more than 350 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:37:08,557 WARNING discord.gateway Shard ID None heartbeat blocked for more than 360 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:37:18,560 WARNING discord.gateway Shard ID None heartbeat blocked for more than 370 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:37:28,564 WARNING discord.gateway Shard ID None heartbeat blocked for more than 380 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:37:38,573 WARNING discord.gateway Shard ID None heartbeat blocked for more than 390 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:37:48,579 WARNING discord.gateway Shard ID None heartbeat blocked for more than 400 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:37:58,585 WARNING discord.gateway Shard ID None heartbeat blocked for more than 410 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:38:08,595 WARNING discord.gateway Shard ID None heartbeat blocked for more than 420 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:38:18,605 WARNING discord.gateway Shard ID None heartbeat blocked for more than 430 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:38:28,614 WARNING discord.gateway Shard ID None heartbeat blocked for more than 440 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 635, in <module>
    keep_alive()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ryrob\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 603, in on_message
    # Don't use this to inject code into the bot tho
  File "<string>", line 1, in <module>

2023-12-12 22:38:30,648 WARNING discord.client PyNaCl is not installed, voice will NOT be supported
2023-12-12 22:38:30,748 DEBUG discord.client on_ready has successfully been registered as an event
2023-12-12 22:38:30,748 DEBUG discord.client on_member_join has successfully been registered as an event
2023-12-12 22:38:30,748 DEBUG discord.client on_message has successfully been registered as an event
2023-12-12 22:38:30,749 DEBUG asyncio Using proactor: IocpProactor
2023-12-12 22:38:30,750 INFO discord.client logging in using static token
2023-12-12 22:38:31,620 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.239:8080
2023-12-12 22:38:31,620 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-12-12 22:38:31,772 INFO discord.gateway Shard ID None has connected to Gateway (Session ID: f892c75822e67a5ca5ae39ac7bd628de).
2023-12-12 22:41:29,157 WARNING discord.client PyNaCl is not installed, voice will NOT be supported
2023-12-12 22:41:29,228 DEBUG discord.client on_ready has successfully been registered as an event
2023-12-12 22:41:29,228 DEBUG discord.client on_member_join has successfully been registered as an event
2023-12-12 22:41:29,228 DEBUG discord.client on_message has successfully been registered as an event
2023-12-12 22:41:29,229 DEBUG asyncio Using proactor: IocpProactor
2023-12-12 22:41:29,230 INFO discord.client logging in using static token
2023-12-12 22:41:29,260 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.239:8080
2023-12-12 22:41:29,260 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-12-12 22:41:30,100 INFO discord.gateway Shard ID None has connected to Gateway (Session ID: 067c1816125708566de2ac458df71e08).
2023-12-12 22:42:14,860 ERROR discord.client Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\main.py", line 605, in on_message
    await message.channel.send(maths_answer)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
2023-12-15 18:46:41,963 WARNING discord.client PyNaCl is not installed, voice will NOT be supported
2023-12-15 18:46:41,965 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): pypi.org:443
2023-12-15 18:46:42,067 DEBUG urllib3.connectionpool https://pypi.org:443 "GET /pypi/praw/json HTTP/1.1" 200 35659
2023-12-15 18:46:43,847 DEBUG discord.client on_ready has successfully been registered as an event
2023-12-15 18:46:43,848 DEBUG discord.client on_member_join has successfully been registered as an event
2023-12-15 18:46:43,848 DEBUG discord.client on_message has successfully been registered as an event
2023-12-15 18:46:43,848 DEBUG asyncio Using proactor: IocpProactor
2023-12-15 18:46:43,850 INFO discord.client logging in using static token
2023-12-15 18:46:44,714 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.239:8080
2023-12-15 18:46:44,714 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-12-15 18:46:44,880 INFO discord.gateway Shard ID None has connected to Gateway (Session ID: 264d081c95bf62c880ad5ccb73cc9c10).
2023-12-15 18:46:53,585 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-15 18:46:53,585 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/newyorknine/hot at 1702666013.5858717
2023-12-15 18:46:53,585 DEBUG prawcore Data: None
2023-12-15 18:46:53,585 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-15 18:46:53,587 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): www.reddit.com:443
2023-12-15 18:46:53,910 DEBUG urllib3.connectionpool https://www.reddit.com:443 "POST /api/v1/access_token HTTP/1.1" 200 653
2023-12-15 18:46:53,917 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): oauth.reddit.com:443
2023-12-15 18:46:55,746 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/newyorknine/hot?limit=200&raw_json=1 HTTP/1.1" 200 91931
2023-12-15 18:46:55,901 DEBUG prawcore Response: 200 (91931 bytes) (rst-186:rem-599.0:used-1 ratelimit) at 1702666015.9013696
2023-12-15 18:46:55,914 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-15 18:46:55,915 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/newyorknine/hot at 1702666015.9153724
2023-12-15 18:46:55,915 DEBUG prawcore Data: None
2023-12-15 18:46:55,915 DEBUG prawcore Params: {'after': 't3_18gkrxl', 'limit': 200, 'raw_json': 1}
2023-12-15 18:46:57,385 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/newyorknine/hot?limit=200&after=t3_18gkrxl&raw_json=1 HTTP/1.1" 200 93438
2023-12-15 18:46:57,657 DEBUG prawcore Response: 200 (93438 bytes) (rst-184:rem-598.0:used-2 ratelimit) at 1702666017.6578484
2023-12-15 18:46:57,671 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-15 18:46:57,671 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/newyorknine/hot at 1702666017.6718507
2023-12-15 18:46:57,671 DEBUG prawcore Data: None
2023-12-15 18:46:57,672 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-15 18:46:59,204 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/newyorknine/hot?limit=200&raw_json=1 HTTP/1.1" 200 91922
2023-12-15 18:47:00,416 DEBUG prawcore Response: 200 (91922 bytes) (rst-183:rem-597.0:used-3 ratelimit) at 1702666020.416948
2023-12-15 18:47:00,429 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-15 18:47:00,429 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/newyorknine/hot at 1702666020.4299502
2023-12-15 18:47:00,429 DEBUG prawcore Data: None
2023-12-15 18:47:00,429 DEBUG prawcore Params: {'after': 't3_18gkrxl', 'limit': 200, 'raw_json': 1}
2023-12-15 18:47:02,240 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/newyorknine/hot?limit=200&after=t3_18gkrxl&raw_json=1 HTTP/1.1" 200 93447
2023-12-15 18:47:02,601 DEBUG prawcore Response: 200 (93447 bytes) (rst-180:rem-596.0:used-4 ratelimit) at 1702666022.6018643
2023-12-15 18:47:02,616 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-15 18:47:02,616 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/newyorknine/hot at 1702666022.6168675
2023-12-15 18:47:02,616 DEBUG prawcore Data: None
2023-12-15 18:47:02,616 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-15 18:47:04,179 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/newyorknine/hot?limit=200&raw_json=1 HTTP/1.1" 200 91944
2023-12-15 18:47:04,420 DEBUG prawcore Response: 200 (91944 bytes) (rst-178:rem-595.0:used-5 ratelimit) at 1702666024.4203565
2023-12-15 18:47:04,433 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-15 18:47:04,433 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/newyorknine/hot at 1702666024.433359
2023-12-15 18:47:04,433 DEBUG prawcore Data: None
2023-12-15 18:47:04,433 DEBUG prawcore Params: {'after': 't3_18gkrxl', 'limit': 200, 'raw_json': 1}
2023-12-15 18:47:06,006 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/newyorknine/hot?limit=200&after=t3_18gkrxl&raw_json=1 HTTP/1.1" 200 93425
2023-12-15 18:47:06,180 DEBUG prawcore Response: 200 (93425 bytes) (rst-176:rem-594.0:used-6 ratelimit) at 1702666026.180359
2023-12-15 18:47:06,194 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-15 18:47:06,194 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/newyorknine/hot at 1702666026.1948614
2023-12-15 18:47:06,194 DEBUG prawcore Data: None
2023-12-15 18:47:06,194 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-15 18:47:07,929 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/newyorknine/hot?limit=200&raw_json=1 HTTP/1.1" 200 91905
2023-12-15 18:47:08,035 DEBUG prawcore Response: 200 (91905 bytes) (rst-174:rem-593.0:used-7 ratelimit) at 1702666028.035359
2023-12-15 18:47:08,047 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-15 18:47:08,047 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/newyorknine/hot at 1702666028.0478613
2023-12-15 18:47:08,047 DEBUG prawcore Data: None
2023-12-15 18:47:08,047 DEBUG prawcore Params: {'after': 't3_18gkrxl', 'limit': 200, 'raw_json': 1}
2023-12-15 18:47:10,315 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/newyorknine/hot?limit=200&after=t3_18gkrxl&raw_json=1 HTTP/1.1" 200 93467
2023-12-15 18:47:10,416 DEBUG prawcore Response: 200 (93467 bytes) (rst-172:rem-592.0:used-8 ratelimit) at 1702666030.4161427
2023-12-15 18:47:10,430 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-15 18:47:10,430 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/newyorknine/hot at 1702666030.4306445
2023-12-15 18:47:10,430 DEBUG prawcore Data: None
2023-12-15 18:47:10,431 DEBUG prawcore Params: {'limit': 200, 'raw_json': 1}
2023-12-15 18:47:12,184 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/newyorknine/hot?limit=200&raw_json=1 HTTP/1.1" 200 91933
2023-12-15 18:47:12,342 DEBUG prawcore Response: 200 (91933 bytes) (rst-170:rem-591.0:used-9 ratelimit) at 1702666032.342852
2023-12-15 18:47:12,355 WARNING praw It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

2023-12-15 18:47:12,355 DEBUG prawcore Fetching: GET https://oauth.reddit.com/r/newyorknine/hot at 1702666032.3558545
2023-12-15 18:47:12,355 DEBUG prawcore Data: None
2023-12-15 18:47:12,355 DEBUG prawcore Params: {'after': 't3_18gkrxl', 'limit': 200, 'raw_json': 1}
2023-12-15 18:47:14,014 DEBUG urllib3.connectionpool https://oauth.reddit.com:443 "GET /r/newyorknine/hot?limit=200&after=t3_18gkrxl&raw_json=1 HTTP/1.1" 200 93420
2023-12-15 18:47:14,155 DEBUG prawcore Response: 200 (93420 bytes) (rst-168:rem-590.0:used-10 ratelimit) at 1702666034.1553738
2023-12-15 18:51:31,372 WARNING discord.client PyNaCl is not installed, voice will NOT be supported
2023-12-15 18:51:31,467 DEBUG discord.client on_ready has successfully been registered as an event
2023-12-15 18:51:31,467 DEBUG discord.client on_member_join has successfully been registered as an event
2023-12-15 18:51:31,467 DEBUG discord.client on_message has successfully been registered as an event
2023-12-15 18:51:31,468 DEBUG asyncio Using proactor: IocpProactor
2023-12-15 18:51:31,468 INFO discord.client logging in using static token
2023-12-15 18:51:32,491 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.239:8080
2023-12-15 18:51:32,491 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-12-15 18:51:33,035 INFO discord.gateway Shard ID None has connected to Gateway (Session ID: e37d39d441096d38297191667cb7b2fd).
2023-12-15 18:54:12,507 ERROR discord.client Attempting a reconnect in 0.77s
Traceback (most recent call last):
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\client.py", line 659, in connect
    await self.ws.poll_event()
  File "C:\Users\ryrob\Documents\Things\Python\Diccy_Bot\venv\lib\site-packages\discord\gateway.py", line 646, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
2023-12-15 18:54:13,580 INFO discord.gateway Shard ID None has successfully RESUMED session e37d39d441096d38297191667cb7b2fd.
